### ISSUE TITLE
Rack v1: plugin.json issues

### ISSUE THREAD

**Issue by cschol** [NicolasNeubauer/noobhour_modules#6]
The manifest validator script found the following issues in your `plugin.json`:

```
Validating noobhour
authorUrl: no URL specified
sourceUrl: no URL specified
```

`authorUrl` is optional, but the `sourceUrl` should be set to the Github source URL.

Thanks!

**Comment by NicolasNeubauer** [comment]
fixed in https://github.com/NicolasNeubauer/noobhour_modules/commit/ba3c35b162e81117446cc2a4a139a79e8ebab03d will update Tag and VCVRack library issue
