### ISSUE TITLE
Baseliner Bug in V1

### ISSUE THREAD

**Issue by Petervos2018** [NicolasNeubauer/noobhour_modules#8]
Hi Nicolas 
I have a problem with Baseliner  and Bsl1r in Rack V1.
In v0.62 it works as expected see. Jpg
![BaselinerBug_cr](https://user-images.githubusercontent.com/46076474/60275576-6e393680-98fa-11e9-84fc-28cbe3872dde.jpg)
When I hit the Trig button I get a gate from BSL1R but not in V1

Here is the file,
[BalelinerBug.zip](https://github.com/NicolasNeubauer/noobhour_modules/files/3335260/BalelinerBug.zip)

Greetings Peter.

**Comment by NicolasNeubauer** [comment]
Hi Peter, thanks for the feedback. Tbh I wasn't aware of that behaviour and I'd tend to say the 0.6 one looks more like a bug no? Why would you expect a gate when switching from one input that's 0 to another one that's 0? It's like an ugly "click" when you switch a (hardware) cable no?

**Comment by Petervos2018** [comment]
Sorry I must be using this thing the wrong way, I use it as a Bernoulli gate. 
The gate receives a gate (trigger) and depending on the probability it emits a high upper abs set to +5v or a low abs set to 0V as seen in the picture.
So if it gets 4 gates depending on the probability it emits 1,2,3,4,or none.
Am I wrong ?
Great for drums you should try it  ! ( in 0.6.2c don't bother in V1 cause that does not work) SMILE

**Comment by NicolasNeubauer** [comment]
ah, no, you're right, I misread the display. will investigate. Also, wrongly added this issue as fixed lol. will follow up!

**Comment by NicolasNeubauer** [comment]
found it. will be out in 1.0.4 (1.0.3 is already in the pipeline so don't be surprised if it's not out with the next release)

**Comment by Petervos2018** [comment]
Well done 
Still at 1.0.3 and you fixed it, Thanks

Peter.
