### ISSUE TITLE
Polyphony in Customscaler

### ISSUE THREAD

**Issue by dag2099** [NicolasNeubauer/noobhour_modules#9]
Platform: windows 7
The manual states:
"Polyphony

If in is polyphonic, v/oct and change will be polyphonic as well,"

I've found this not to be true. I've tried controlling Customscaler with both my keyboard with other modules, attaching a poly input to both "in" and v/oct simply activates or deactivates the first note provided in the poly signal in v/oct.

Hope this is clear, thanks.

**Comment by dag2099** [comment]
Okay, I think I may have misunderstood what your manual says. I am talking about the bit of the module that allows you to turn notes on and off in the quantizer, which I had assumed would be polyphonic. It seems I misread your manual and the bit that I quoted was actually talking about the output section. Either way it would still be really useful to be able to program the module polyphonicly.

**Comment by NicolasNeubauer** [comment]
Hey, thanks for the feedback - you're right, the programming part isn't polyphonic so far, but it should be. Will add to the next release!

**Comment by NicolasNeubauer** [comment]
Fixed in https://github.com/NicolasNeubauer/noobhour_modules/releases/tag/1.0.3 which is on its way to publication. Please feel free to re-open if you encounter any issues.
